name: 'Publish action versions'
description: 'Move the major.minor version tag to point to a specified ref'
inputs:
  source-tag:
    description: 'Tag name that the major.minor tag will point to. Examples: v1.2.3, 1.2.3'
    required: true
  token:
    description: 'Token to get an authenticated Octokit'
    default: ${{ github.token }}
outputs:
  major-minor-tag:
    description: 'The major.minor version tag that has been updated (created). Examples: v1.2, 1.2'
runs:
  using: 'node20'
  main: 'dist/index.js'
